version: "3.8"
services:
  client-dev:
    container_name: client-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - name=value
    env_file:
      - .env.development
    depends_on:
      - db-dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
  client-prod:
    container_name: client-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    env_file:
      - .env.production
  db-dev:
    container_name: db-dev
    image: postgres:16.2-alpine
    expose:
    - "6520" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "6520:6520"
    environment:
      - name=value
    env_file:
      - .env.development
    command: -p 6520