FROM node:20.11.0

RUN npm install -g @prisma/cli

WORKDIR /app

COPY package*.json .

RUN npm install

COPY prisma ./prisma

RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
