FROM node:20.11.0

RUN npm install -g pnpm

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install

COPY prisma ./prisma

COPY . .

RUN pnpm dlx prisma migrate dev

EXPOSE 3000

CMD [ "pnpm", "run", "dev" ]
